package viper

import (
	"gitlab.com/verygoodsoftwarenotvirus/naff/forks/jennifer/jen"
	"gitlab.com/verygoodsoftwarenotvirus/naff/lib/utils"
	"gitlab.com/verygoodsoftwarenotvirus/naff/models"
)

func keysDotGo(proj *models.Project) *jen.File {
	code := jen.NewFile(packageName)

	utils.AddImports(proj, code, false)

	code.Add(
		jen.Var().Defs(
			jen.ID("x").Op("=").Lit("."),
			jen.ID("debugKey").Op("=").Lit("debug"),
			jen.ID("enabledKey").Op("=").Lit("enabled"),
			jen.ID("metaKey").Op("=").Lit("meta"),
			jen.ID("ConfigKeyMetaDebug").Op("=").ID("metaKey").Op("+").ID("x").Op("+").ID("debugKey"),
			jen.ID("ConfigKeyMetaRunMode").Op("=").ID("metaKey").Op("+").ID("x").Op("+").Lit("run_mode"),
			jen.ID("serverKey").Op("=").Lit("server"),
			jen.ID("ConfigKeyServerHTTPPort").Op("=").ID("serverKey").Op("+").ID("x").Op("+").Lit("http_port"),
			jen.ID("ConfigKeyServerStartupDeadline").Op("=").ID("serverKey").Op("+").ID("x").Op("+").Lit("startup_deadline"),
			jen.ID("ConfigKeyServerDebug").Op("=").ID("serverKey").Op("+").ID("x").Op("+").ID("debugKey"),
			jen.ID("encodingKey").Op("=").Lit("encoding"),
			jen.ID("ConfigKeyEncodingContentType").Op("=").ID("encodingKey").Op("+").ID("x").Op("+").Lit("content_type"),
			jen.ID("frontendKey").Op("=").Lit("frontend"),
			jen.ID("ConfigKeyFrontendDebug").Op("=").ID("frontendKey").Op("+").ID("x").Op("+").ID("debugKey"),
			jen.ID("ConfigKeyFrontendUseFakeData").Op("=").ID("frontendKey").Op("+").ID("x").Op("+").Lit("use_fake_data"),
			jen.ID("authKey").Op("=").Lit("auth"),
			jen.ID("ConfigKeyAuthDebug").Op("=").ID("authKey").Op("+").ID("x").Op("+").ID("debugKey"),
			jen.ID("cookiesKey").Op("=").Lit("cookies"),
			jen.ID("ConfigKeyAuthCookieName").Op("=").ID("authKey").Op("+").ID("x").Op("+").ID("cookiesKey").Op("+").ID("x").Op("+").Lit("name"),
			jen.ID("ConfigKeyAuthCookieDomain").Op("=").ID("authKey").Op("+").ID("x").Op("+").ID("cookiesKey").Op("+").ID("x").Op("+").Lit("domain"),
			jen.ID("ConfigKeyAuthCookieHashKey").Op("=").ID("authKey").Op("+").ID("x").Op("+").ID("cookiesKey").Op("+").ID("x").Op("+").Lit("hash_key"),
			jen.ID("ConfigKeyAuthCookieSigningKey").Op("=").ID("authKey").Op("+").ID("x").Op("+").ID("cookiesKey").Op("+").ID("x").Op("+").Lit("signing_key"),
			jen.ID("ConfigKeyAuthCookieLifetime").Op("=").ID("authKey").Op("+").ID("x").Op("+").ID("cookiesKey").Op("+").ID("x").Op("+").Lit("lifetime"),
			jen.ID("ConfigKeyAuthSecureCookiesOnly").Op("=").ID("authKey").Op("+").ID("x").Op("+").ID("cookiesKey").Op("+").ID("x").Op("+").Lit("secure_only"),
			jen.ID("capitalismKey").Op("=").Lit("capitalism"),
			jen.ID("providerKey").Op("=").Lit("provider"),
			jen.ID("stripeKey").Op("=").Lit("stripe"),
			jen.ID("ConfigKeyCapitalismEnabled").Op("=").ID("capitalismKey").Op("+").ID("x").Op("+").ID("enabledKey"),
			jen.ID("ConfigKeyCapitalismProvider").Op("=").ID("capitalismKey").Op("+").ID("x").Op("+").ID("providerKey"),
			jen.ID("ConfigKeyCapitalismStripeAPIKey").Op("=").ID("capitalismKey").Op("+").ID("x").Op("+").ID("stripeKey").Op("+").ID("x").Op("+").Lit("api_key"),
			jen.ID("ConfigKeyCapitalismStripeSuccessURL").Op("=").ID("capitalismKey").Op("+").ID("x").Op("+").ID("stripeKey").Op("+").ID("x").Op("+").Lit("success_url"),
			jen.ID("ConfigKeyCapitalismStripeCancelURL").Op("=").ID("capitalismKey").Op("+").ID("x").Op("+").ID("stripeKey").Op("+").ID("x").Op("+").Lit("cancel_url"),
			jen.ID("ConfigKeyCapitalismStripeWebhookSecret").Op("=").ID("capitalismKey").Op("+").ID("x").Op("+").ID("stripeKey").Op("+").ID("x").Op("+").Lit("webhook_secret"),
			jen.ID("pasetoKey").Op("=").Lit("paseto"),
			jen.ID("ConfigKeyAuthPASETOLifetimeKey").Op("=").ID("authKey").Op("+").ID("x").Op("+").ID("pasetoKey").Op("+").ID("x").Op("+").Lit("lifetime"),
			jen.ID("ConfigKeyAuthPASETOListener").Op("=").ID("authKey").Op("+").ID("x").Op("+").ID("pasetoKey").Op("+").ID("x").Op("+").Lit("issuer"),
			jen.ID("ConfigKeyAuthPASETOLocalModeKey").Op("=").ID("authKey").Op("+").ID("x").Op("+").ID("pasetoKey").Op("+").ID("x").Op("+").Lit("local_mode_key"),
			jen.ID("ConfigKeyAuthEnableUserSignup").Op("=").ID("authKey").Op("+").ID("x").Op("+").Lit("enable_user_signup"),
			jen.ID("ConfigKeyAuthMinimumUsernameLength").Op("=").ID("authKey").Op("+").ID("x").Op("+").Lit("minimum_username_length"),
			jen.ID("ConfigKeyAuthMinimumPasswordLength").Op("=").ID("authKey").Op("+").ID("x").Op("+").Lit("minimum_password_length"),
			jen.ID("observabilityKey").Op("=").Lit("observability"),
			jen.ID("metricsKey").Op("=").Lit("metrics"),
			jen.ID("tracingKey").Op("=").Lit("tracing"),
			jen.ID("ConfigKeyMetricsProvider").Op("=").ID("observabilityKey").Op("+").ID("x").Op("+").ID("metricsKey").Op("+").ID("x").Op("+").Lit("provider"),
			jen.ID("ConfigKeyMetricsRuntimeCollectionInterval").Op("=").ID("observabilityKey").Op("+").ID("x").Op("+").ID("metricsKey").Op("+").ID("x").Op("+").Lit("runtime_metrics_collection_interval"),
			jen.ID("ConfigKeyObservabilityTracingProvider").Op("=").ID("observabilityKey").Op("+").ID("x").Op("+").ID("tracingKey").Op("+").ID("x").Op("+").Lit("provider"),
			jen.ID("ConfigKeyObservabilityTracingSpanCollectionProbability").Op("=").ID("observabilityKey").Op("+").ID("x").Op("+").ID("tracingKey").Op("+").ID("x").Op("+").Lit("span_collection_probability"),
			jen.ID("jaegerKey").Op("=").ID("observabilityKey").Op("+").ID("x").Op("+").ID("tracingKey").Op("+").ID("x").Op("+").Lit("jaeger"),
			jen.ID("ConfigKeyObservabilityTracingJaegerCollectorEndpoint").Op("=").ID("jaegerKey").Op("+").ID("x").Op("+").Lit("collector_endpoint"),
			jen.ID("ConfigKeyObservabilityTracingJaegerServiceName").Op("=").ID("jaegerKey").Op("+").ID("x").Op("+").Lit("service_name"),
			jen.ID("databaseKey").Op("=").Lit("database"),
			jen.ID("ConfigKeyDatabaseDebug").Op("=").ID("databaseKey").Op("+").ID("x").Op("+").ID("debugKey"),
			jen.ID("ConfigKeyDatabaseProvider").Op("=").ID("databaseKey").Op("+").ID("x").Op("+").Lit("provider"),
			jen.ID("ConfigKeyDatabaseMaxPingAttempts").Op("=").ID("databaseKey").Op("+").ID("x").Op("+").Lit("max_ping_attempts"),
			jen.ID("ConfigKeyDatabaseConnectionDetails").Op("=").ID("databaseKey").Op("+").ID("x").Op("+").Lit("connection_details"),
			jen.ID("createTestUserKey").Op("=").Lit("create_test_user"),
			jen.ID("ConfigKeyDatabaseCreateTestUserUsername").Op("=").ID("databaseKey").Op("+").ID("x").Op("+").ID("createTestUserKey").Op("+").ID("x").Op("+").Lit("username"),
			jen.ID("ConfigKeyDatabaseCreateTestUserPassword").Op("=").ID("databaseKey").Op("+").ID("x").Op("+").ID("createTestUserKey").Op("+").ID("x").Op("+").Lit("password"),
			jen.ID("ConfigKeyDatabaseCreateTestUserIsServiceAdmin").Op("=").ID("databaseKey").Op("+").ID("x").Op("+").ID("createTestUserKey").Op("+").ID("x").Op("+").Lit("is_site_admin"),
			jen.ID("ConfigKeyDatabaseCreateTestUserHashedPassword").Op("=").ID("databaseKey").Op("+").ID("x").Op("+").ID("createTestUserKey").Op("+").ID("x").Op("+").Lit("hashed_password"),
			jen.ID("ConfigKeyDatabaseRunMigrations").Op("=").ID("databaseKey").Op("+").ID("x").Op("+").Lit("run_migrations"),
			jen.ID("ConfigKeyDatabaseMetricsCollectionInterval").Op("=").ID("databaseKey").Op("+").ID("x").Op("+").Lit("metrics_collection_interval"),
			jen.ID("searchKey").Op("=").Lit("search"),
			jen.ID("ConfigKeySearchProvider").Op("=").ID("searchKey").Op("+").ID("x").Op("+").Lit("provider"),
			jen.ID("ConfigKeyItemsSearchIndexPath").Op("=").ID("searchKey").Op("+").ID("x").Op("+").Lit("items_index_path"),
			jen.ID("uploadsKey").Op("=").Lit("uploads"),
			jen.ID("storageConfigKey").Op("=").Lit("storage_config"),
			jen.ID("ConfigKeyUploaderProvider").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").Lit("provider"),
			jen.ID("ConfigKeyUploaderDebug").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").Lit("debug"),
			jen.ID("ConfigKeyUploaderBucketName").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").Lit("bucket_name"),
			jen.ID("ConfigKeyUploaderUploadFilename").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").Lit("upload_filename_key"),
			jen.ID("azureKey").Op("=").Lit("azure"),
			jen.ID("ConfigKeyUploaderAzureAuthMethod").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").ID("azureKey").Op("+").ID("x").Op("+").Lit("auth_method"),
			jen.ID("ConfigKeyUploaderAzureAccountName").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").ID("azureKey").Op("+").ID("x").Op("+").Lit("account_name"),
			jen.ID("ConfigKeyUploaderAzureBucketName").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").ID("azureKey").Op("+").ID("x").Op("+").Lit("bucket_name"),
			jen.ID("retryingKey").Op("=").Lit("retrying"),
			jen.ID("ConfigKeyUploaderAzureMaxTries").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").ID("azureKey").Op("+").ID("x").Op("+").ID("retryingKey").Op("+").ID("x").Op("+").Lit("max_tries"),
			jen.ID("ConfigKeyUploaderAzureTryTimeout").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").ID("azureKey").Op("+").ID("x").Op("+").ID("retryingKey").Op("+").ID("x").Op("+").Lit("try_timeout"),
			jen.ID("ConfigKeyUploaderAzureRetryDelay").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").ID("azureKey").Op("+").ID("x").Op("+").ID("retryingKey").Op("+").ID("x").Op("+").Lit("retry_delay"),
			jen.ID("ConfigKeyUploaderAzureMaxRetryDelay").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").ID("azureKey").Op("+").ID("x").Op("+").ID("retryingKey").Op("+").ID("x").Op("+").Lit("max_retry_delay"),
			jen.ID("ConfigKeyUploaderAzureRetryReadsFromSecondaryHost").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").ID("azureKey").Op("+").ID("x").Op("+").ID("retryingKey").Op("+").ID("x").Op("+").Lit("retry_reads_from_secondary_host"),
			jen.ID("ConfigKeyUploaderAzureTokenCredentialsInitialToken").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").ID("azureKey").Op("+").ID("x").Op("+").Lit("token_creds_initial_token"),
			jen.ID("ConfigKeyUploaderAzureSharedKeyAccountKey").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").ID("azureKey").Op("+").ID("x").Op("+").Lit("shared_key_account_key"),
			jen.ID("gcsKey").Op("=").Lit("gcs"),
			jen.ID("ConfigKeyUploaderGCSAccountKeyFilepath").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").ID("gcsKey").Op("+").ID("x").Op("+").Lit("service_account_key_filepath"),
			jen.ID("ConfigKeyUploaderGCSScopes").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").ID("gcsKey").Op("+").ID("x").Op("+").Lit("scopes"),
			jen.ID("ConfigKeyUploaderGCSBucketName").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").ID("gcsKey").Op("+").ID("x").Op("+").Lit("bucket_name"),
			jen.ID("blobSettingsKey").Op("=").Lit("blob_settings"),
			jen.ID("ConfigKeyUploaderGCSGoogleAccessID").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").ID("gcsKey").Op("+").ID("x").Op("+").ID("blobSettingsKey").Op("+").ID("x").Op("+").Lit("google_access_id"),
			jen.ID("s3Key").Op("=").Lit("s3"),
			jen.ID("ConfigKeyUploaderS3BucketName").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").ID("s3Key").Op("+").ID("x").Op("+").Lit("bucket_name"),
			jen.ID("filesystemKey").Op("=").Lit("filesystem"),
			jen.ID("ConfigKeyUploaderFilesystemRootDirectory").Op("=").ID("uploadsKey").Op("+").ID("x").Op("+").ID("storageConfigKey").Op("+").ID("x").Op("+").ID("filesystemKey").Op("+").ID("x").Op("+").Lit("root_directory"),
			jen.ID("auditLogKey").Op("=").Lit("audit_log"),
			jen.ID("ConfigKeyAuditLogEnabled").Op("=").ID("auditLogKey").Op("+").ID("x").Op("+").ID("enabledKey"),
			jen.ID("webhooksKey").Op("=").Lit("webhooks"),
			jen.ID("ConfigKeyWebhooksEnabled").Op("=").ID("webhooksKey").Op("+").ID("x").Op("+").ID("enabledKey"),
		),
		jen.Line(),
	)

	return code
}
