package auth

import (
	jen "gitlab.com/verygoodsoftwarenotvirus/naff/forks/jennifer/jen"
	utils "gitlab.com/verygoodsoftwarenotvirus/naff/lib/utils"
	"gitlab.com/verygoodsoftwarenotvirus/naff/models"
)

func httpRoutesTestDotGo(proj *models.Project) *jen.File {
	ret := jen.NewFile("auth")

	utils.AddImports(proj, ret)

	ret.Add(
		jen.Func().ID("TestService_DecodeCookieFromRequest").Params(jen.ID("T").ParamPointer().Qual("testing", "T")).Block(
			jen.ID("T").Dot("Parallel").Call(),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("happy path"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/api/v1/something"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.List(jen.ID("c"), jen.Err()).Assign().ID("s").Dot("buildAuthCookie").Call(jen.VarPointer().Qual(proj.ModelsV1Package(), "User").Values(
					jen.ID("ID").MapAssign().Add(utils.FakeUint64Func()),
					jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc())),
				),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.ID("req").Dot("AddCookie").Call(jen.ID("c")),
				jen.Line(),
				jen.List(jen.ID("cookie"), jen.Err()).Assign().ID("s").Dot("DecodeCookieFromRequest").Call(jen.ID("req").Dot("Context").Call(), jen.ID("req")),
				utils.AssertNoError(jen.Err(), nil),
				utils.AssertNotNil(jen.ID("cookie"), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with invalid cookie"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/api/v1/something"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.Comment("begin building bad cookie"),
				jen.Comment("NOTE: any code here is duplicated from service.buildAuthCookie"),
				jen.Comment("any changes made there might need to be reflected here"),
				jen.ID("c").Assign().VarPointer().Qual("net/http", "Cookie").Valuesln(
					jen.ID("Name").MapAssign().ID("CookieName"),
					jen.ID("Value").MapAssign().Lit("blah blah blah this is not a real cookie"),
					jen.ID("Path").MapAssign().Lit("/"),
					jen.ID("HttpOnly").MapAssign().ID("true"),
				),
				jen.Comment("end building bad cookie"),
				jen.ID("req").Dot("AddCookie").Call(jen.ID("c")),
				jen.Line(),
				jen.List(jen.ID("cookie"), jen.Err()).Assign().ID("s").Dot("DecodeCookieFromRequest").Call(jen.ID("req").Dot("Context").Call(), jen.ID("req")),
				utils.AssertError(jen.Err(), nil),
				utils.AssertNil(jen.ID("cookie"), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("without cookie"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/api/v1/something"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.List(jen.ID("cookie"), jen.Err()).Assign().ID("s").Dot("DecodeCookieFromRequest").Call(jen.ID("req").Dot("Context").Call(), jen.ID("req")),
				utils.AssertError(jen.Err(), nil),
				utils.AssertEqual(jen.Err(), jen.Qual("net/http", "ErrNoCookie"), nil),
				utils.AssertNil(jen.ID("cookie"), nil),
			)),
		),
		jen.Line(),
	)

	ret.Add(
		jen.Func().ID("TestService_WebsocketAuthFunction").Params(jen.ID("T").ParamPointer().Qual("testing", "T")).Block(
			jen.ID("T").Dot("Parallel").Call(),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with valid oauth2 client"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("expected").Assign().VarPointer().Qual(proj.ModelsV1Package(), "OAuth2Client").Values(),
				jen.ID("s").Dot("oauth2ClientsService").Assert(jen.PointerTo().ID("mockOAuth2ClientValidator")).Dot("On").Callln(
					jen.Lit("ExtractOAuth2ClientFromRequest"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.ID("expected"), jen.Nil()),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.ID("actual").Assign().ID("s").Dot("WebsocketAuthFunction").Call(jen.ID("req")),
				utils.AssertTrue(jen.ID("actual"), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with valid cookie"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("oac").Assign().VarPointer().Qual(proj.ModelsV1Package(), "OAuth2Client").Values(),
				jen.ID("s").Dot("oauth2ClientsService").Assert(jen.PointerTo().ID("mockOAuth2ClientValidator")).Dot("On").Callln(
					jen.Lit("ExtractOAuth2ClientFromRequest"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.ID("oac"), jen.Qual("errors", "New").Call(jen.Lit("blah"))),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.List(jen.ID("c"), jen.Err()).Assign().ID("s").Dot("buildAuthCookie").Call(jen.VarPointer().Qual(proj.ModelsV1Package(), "User").Values(jen.ID("ID").MapAssign().Add(utils.FakeUint64Func()), jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc()))),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.ID("req").Dot("AddCookie").Call(jen.ID("c")),
				jen.Line(),
				jen.ID("actual").Assign().ID("s").Dot("WebsocketAuthFunction").Call(jen.ID("req")),
				utils.AssertTrue(jen.ID("actual"), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with nothing"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("oac").Assign().VarPointer().Qual(proj.ModelsV1Package(), "OAuth2Client").Values(),
				jen.ID("s").Dot("oauth2ClientsService").Assert(jen.PointerTo().ID("mockOAuth2ClientValidator")).Dot("On").Callln(
					jen.Lit("ExtractOAuth2ClientFromRequest"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.ID("oac"), jen.Qual("errors", "New").Call(jen.Lit("blah"))),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.ID("actual").Assign().ID("s").Dot("WebsocketAuthFunction").Call(jen.ID("req")),
				utils.AssertFalse(jen.ID("actual"), nil),
			)),
		),
		jen.Line(),
	)

	ret.Add(
		jen.Func().ID("TestService_FetchUserFromRequest").Params(jen.ID("T").ParamPointer().Qual("testing", "T")).Block(
			jen.ID("T").Dot("Parallel").Call(),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("happy path"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("userID").Assign().Add(utils.FakeUint64Func()),
				jen.ID("expectedUser").Assign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(
					jen.ID("ID").MapAssign().ID("userID"),
					jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc()),
				),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.List(jen.ID("c"), jen.Err()).Assign().ID("s").Dot("buildAuthCookie").Call(jen.ID("expectedUser")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.ID("req").Dot("AddCookie").Call(jen.ID("c")),
				jen.Line(),
				jen.ID("s").Dot("userDB").Assert(jen.PointerTo().Qual(proj.ModelsV1Package("mock"), "UserDataManager")).Dot("On").Callln(
					jen.Lit("GetUser"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.ID("userID"),
				).Dot("Return").Call(jen.ID("expectedUser"), jen.Nil()),
				jen.Line(),
				jen.List(jen.ID("actualUser"), jen.Err()).Assign().ID("s").Dot("FetchUserFromRequest").Call(jen.ID("req").Dot("Context").Call(), jen.ID("req")),
				utils.AssertEqual(jen.ID("expectedUser"), jen.ID("actualUser"), nil),
				utils.AssertNoError(jen.Err(), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("without cookie"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("userID").Assign().Add(utils.FakeUint64Func()),
				jen.ID("expectedUser").Assign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(
					jen.ID("ID").MapAssign().ID("userID"),
					jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc()),
				),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.ID("s").Dot("userDB").Assert(jen.PointerTo().Qual(proj.ModelsV1Package("mock"), "UserDataManager")).Dot("On").Callln(
					jen.Lit("GetUser"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.ID("userID"),
				).Dot("Return").Call(jen.ID("expectedUser"), jen.Nil()),
				jen.Line(),
				jen.List(jen.ID("actualUser"), jen.Err()).Assign().ID("s").Dot("FetchUserFromRequest").Call(jen.ID("req").Dot("Context").Call(), jen.ID("req")),
				utils.AssertNil(jen.ID("actualUser"), nil),
				utils.AssertError(jen.Err(), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with error fetching user"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("userID").Assign().Add(utils.FakeUint64Func()),
				jen.ID("expectedUser").Assign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(
					jen.ID("ID").MapAssign().ID("userID"),
					jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc()),
				),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.List(jen.ID("c"), jen.Err()).Assign().ID("s").Dot("buildAuthCookie").Call(jen.ID("expectedUser")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.ID("req").Dot("AddCookie").Call(jen.ID("c")),
				jen.Line(),
				jen.ID("expectedError").Assign().Qual("errors", "New").Call(jen.Lit("blah")),
				jen.ID("s").Dot("userDB").Assert(jen.PointerTo().Qual(proj.ModelsV1Package("mock"), "UserDataManager")).Dot("On").Callln(
					jen.Lit("GetUser"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.ID("userID"),
				).Dot("Return").Call(jen.Parens(jen.PointerTo().Qual(proj.ModelsV1Package(), "User")).Call(jen.Nil()), jen.ID("expectedError")),
				jen.Line(),
				jen.List(jen.ID("actualUser"), jen.Err()).Assign().ID("s").Dot("FetchUserFromRequest").Call(jen.ID("req").Dot("Context").Call(), jen.ID("req")),
				utils.AssertNil(jen.ID("actualUser"), nil),
				utils.AssertError(jen.Err(), nil),
			)),
		),
		jen.Line(),
	)

	ret.Add(
		jen.Func().ID("TestService_Login").Params(jen.ID("T").ParamPointer().Qual("testing", "T")).Block(
			jen.ID("T").Dot("Parallel").Call(),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("happy path"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("expectedUser").Assign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc())),
				jen.ID("s").Dot("userDB").Assert(jen.PointerTo().Qual(proj.ModelsV1Package("mock"), "UserDataManager")).Dot("On").Callln(
					jen.Lit("GetUserByUsername"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.ID("expectedUser").Dot("Username"),
				).Dot("Return").Call(jen.ID("expectedUser"), jen.Nil()),
				jen.Line(),
				jen.ID("s").Dot("authenticator").Assert(jen.PointerTo().Qual(proj.InternalAuthV1Package("mock"), "Authenticator")).Dot("On").Callln(
					jen.Lit("ValidateLogin"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.ID("true"), jen.Nil()),
				jen.Line(),
				jen.ID("exampleLoginData").Assign().VarPointer().Qual(proj.ModelsV1Package(), "UserLoginInput").Valuesln(
					jen.ID("Username").MapAssign().ID("expectedUser").Dot("Username"),
					jen.ID("Password").MapAssign().Add(utils.FakePasswordFunc()),
					jen.ID("TOTPToken").MapAssign().Lit("123456"),
				),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.ID("res").Assign().ID("httptest").Dot("NewRecorder").Call(),
				jen.ID("req").Equals().ID("req").Dot("WithContext").Call(jen.Qual("context", "WithValue").Call(jen.ID("req").Dot("Context").Call(), jen.ID("UserLoginInputMiddlewareCtxKey"), jen.ID("exampleLoginData"))),
				jen.Line(),
				jen.ID("s").Dot("LoginHandler").Call().Call(jen.ID("res"), jen.ID("req")),
				jen.Line(),
				utils.AssertEqual(jen.ID("res").Dot("Code"), jen.Qual("net/http", "StatusNoContent"), nil),
				utils.AssertNotEmpty(jen.ID("res").Dot("Header").Call().Dot("Get").Call(jen.Lit("Set-Cookie")), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with error fetching login data from request"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("expectedUser").Assign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc())),
				jen.ID("s").Dot("userDB").Assert(jen.PointerTo().Qual(proj.ModelsV1Package("mock"), "UserDataManager")).Dot("On").Callln(
					jen.Lit("GetUserByUsername"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.ID("expectedUser").Dot("Username"),
				).Dot("Return").Call(jen.ID("expectedUser"), jen.Qual("errors", "New").Call(jen.Lit("arbitrary"))),
				jen.Line(),
				jen.ID("exampleLoginData").Assign().VarPointer().Qual(proj.ModelsV1Package(), "UserLoginInput").Valuesln(
					jen.ID("Username").MapAssign().ID("expectedUser").Dot("Username"),
					jen.ID("Password").MapAssign().Add(utils.FakePasswordFunc()),
					jen.ID("TOTPToken").MapAssign().Lit("123456"),
				),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.ID("res").Assign().ID("httptest").Dot("NewRecorder").Call(),
				jen.ID("req").Equals().ID("req").Dot("WithContext").Call(jen.Qual("context", "WithValue").Call(jen.ID("req").Dot("Context").Call(), jen.ID("UserLoginInputMiddlewareCtxKey"), jen.ID("exampleLoginData"))),
				jen.Line(),
				jen.ID("s").Dot("LoginHandler").Call().Call(jen.ID("res"), jen.ID("req")),
				jen.Line(),
				utils.AssertEqual(jen.ID("res").Dot("Code"), jen.Qual("net/http", "StatusUnauthorized"), nil),
				utils.AssertEmpty(jen.ID("res").Dot("Header").Call().Dot("Get").Call(jen.Lit("Set-Cookie")), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with error encoding error fetching login data"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("ed").Assign().VarPointer().Qual(proj.InternalEncodingV1Package("mock"), "EncoderDecoder").Values(),
				jen.ID("ed").Dot("On").Callln(
					jen.Lit("EncodeResponse"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.Qual("errors", "New").Call(jen.Lit("blah"))),
				jen.ID("s").Dot("encoderDecoder").Equals().ID("ed"),
				jen.Line(),
				jen.ID("expectedUser").Assign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc())),
				jen.ID("s").Dot("userDB").Assert(jen.PointerTo().Qual(proj.ModelsV1Package("mock"), "UserDataManager")).Dot("On").Callln(
					jen.Lit("GetUserByUsername"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.ID("expectedUser").Dot("Username"),
				).Dot("Return").Call(jen.ID("expectedUser"), jen.Qual("errors", "New").Call(jen.Lit("arbitrary"))),
				jen.Line(),
				jen.ID("exampleLoginData").Assign().VarPointer().Qual(proj.ModelsV1Package(), "UserLoginInput").Valuesln(
					jen.ID("Username").MapAssign().ID("expectedUser").Dot("Username"),
					jen.ID("Password").MapAssign().Add(utils.FakePasswordFunc()),
					jen.ID("TOTPToken").MapAssign().Lit("123456"),
				),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.ID("res").Assign().ID("httptest").Dot("NewRecorder").Call(),
				jen.ID("req").Equals().ID("req").Dot("WithContext").Call(jen.Qual("context", "WithValue").Call(jen.ID("req").Dot("Context").Call(), jen.ID("UserLoginInputMiddlewareCtxKey"), jen.ID("exampleLoginData"))),
				jen.Line(),
				jen.ID("s").Dot("LoginHandler").Call().Call(jen.ID("res"), jen.ID("req")),
				jen.Line(),
				utils.AssertEqual(jen.ID("res").Dot("Code"), jen.Qual("net/http", "StatusUnauthorized"), nil),
				utils.AssertEmpty(jen.ID("res").Dot("Header").Call().Dot("Get").Call(jen.Lit("Set-Cookie")), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with invalid login"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("expectedUser").Assign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc())),
				jen.ID("s").Dot("userDB").Assert(jen.PointerTo().Qual(proj.ModelsV1Package("mock"), "UserDataManager")).Dot("On").Callln(
					jen.Lit("GetUserByUsername"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.ID("expectedUser").Dot("Username"),
				).Dot("Return").Call(jen.ID("expectedUser"), jen.Nil()),
				jen.Line(),
				jen.ID("s").Dot("authenticator").Assert(jen.PointerTo().Qual(proj.InternalAuthV1Package("mock"), "Authenticator")).Dot("On").Callln(
					jen.Lit("ValidateLogin"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.ID("false"), jen.Nil()),
				jen.Line(),
				jen.ID("exampleLoginData").Assign().VarPointer().Qual(proj.ModelsV1Package(), "UserLoginInput").Valuesln(
					jen.ID("Username").MapAssign().ID("expectedUser").Dot("Username"),
					jen.ID("Password").MapAssign().Add(utils.FakePasswordFunc()),
					jen.ID("TOTPToken").MapAssign().Lit("123456"),
				),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.ID("res").Assign().ID("httptest").Dot("NewRecorder").Call(),
				jen.ID("req").Equals().ID("req").Dot("WithContext").Call(jen.Qual("context", "WithValue").Call(jen.ID("req").Dot("Context").Call(), jen.ID("UserLoginInputMiddlewareCtxKey"), jen.ID("exampleLoginData"))),
				jen.Line(),
				jen.ID("s").Dot("LoginHandler").Call().Call(jen.ID("res"), jen.ID("req")),
				jen.Line(),
				utils.AssertEqual(jen.ID("res").Dot("Code"), jen.Qual("net/http", "StatusUnauthorized"), nil),
				utils.AssertEmpty(jen.ID("res").Dot("Header").Call().Dot("Get").Call(jen.Lit("Set-Cookie")), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with error validating login"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("expectedUser").Assign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc())),
				jen.ID("s").Dot("userDB").Assert(jen.PointerTo().Qual(proj.ModelsV1Package("mock"), "UserDataManager")).Dot("On").Callln(
					jen.Lit("GetUserByUsername"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.ID("expectedUser").Dot("Username"),
				).Dot("Return").Call(jen.ID("expectedUser"), jen.Nil()),
				jen.Line(),
				jen.ID("s").Dot("authenticator").Assert(jen.PointerTo().Qual(proj.InternalAuthV1Package("mock"), "Authenticator")).Dot("On").Callln(
					jen.Lit("ValidateLogin"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.ID("true"), jen.Qual("errors", "New").Call(jen.Lit("blah"))),
				jen.Line(),
				jen.ID("exampleLoginData").Assign().VarPointer().Qual(proj.ModelsV1Package(), "UserLoginInput").Valuesln(
					jen.ID("Username").MapAssign().ID("expectedUser").Dot("Username"),
					jen.ID("Password").MapAssign().Add(utils.FakePasswordFunc()),
					jen.ID("TOTPToken").MapAssign().Lit("123456"),
				),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.ID("res").Assign().ID("httptest").Dot("NewRecorder").Call(),
				jen.ID("req").Equals().ID("req").Dot("WithContext").Call(jen.Qual("context", "WithValue").Call(jen.ID("req").Dot("Context").Call(), jen.ID("UserLoginInputMiddlewareCtxKey"), jen.ID("exampleLoginData"))),
				jen.Line(),
				jen.ID("s").Dot("LoginHandler").Call().Call(jen.ID("res"), jen.ID("req")),
				jen.Line(),
				utils.AssertEqual(jen.ID("res").Dot("Code"), jen.Qual("net/http", "StatusUnauthorized"), nil),
				utils.AssertEmpty(jen.ID("res").Dot("Header").Call().Dot("Get").Call(jen.Lit("Set-Cookie")), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with error building cookie"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("cb").Assign().VarPointer().ID("mockCookieEncoderDecoder").Values(),
				jen.ID("cb").Dot("On").Callln(
					jen.Lit("Encode"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything")).Dot("Return").Call(jen.Lit(""), jen.Qual("errors", "New").Call(jen.Lit("blah"))),
				jen.ID("s").Dot("cookieManager").Equals().ID("cb"),
				jen.Line(),
				jen.ID("expectedUser").Assign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc())),
				jen.ID("s").Dot("userDB").Assert(jen.PointerTo().Qual(proj.ModelsV1Package("mock"), "UserDataManager")).Dot("On").Callln(
					jen.Lit("GetUserByUsername"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.ID("expectedUser").Dot("Username"),
				).Dot("Return").Call(jen.ID("expectedUser"), jen.Nil()),
				jen.Line(),
				jen.ID("s").Dot("authenticator").Assert(jen.PointerTo().Qual(proj.InternalAuthV1Package("mock"), "Authenticator")).Dot("On").Callln(
					jen.Lit("ValidateLogin"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.ID("true"), jen.Nil()),
				jen.Line(),
				jen.ID("exampleLoginData").Assign().VarPointer().Qual(proj.ModelsV1Package(), "UserLoginInput").Valuesln(
					jen.ID("Username").MapAssign().ID("expectedUser").Dot("Username"),
					jen.ID("Password").MapAssign().Add(utils.FakePasswordFunc()),
					jen.ID("TOTPToken").MapAssign().Lit("123456"),
				),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.ID("res").Assign().ID("httptest").Dot("NewRecorder").Call(),
				jen.ID("req").Equals().ID("req").Dot("WithContext").Call(jen.Qual("context", "WithValue").Call(jen.ID("req").Dot("Context").Call(), jen.ID("UserLoginInputMiddlewareCtxKey"), jen.ID("exampleLoginData"))),
				jen.Line(),
				jen.ID("s").Dot("LoginHandler").Call().Call(jen.ID("res"), jen.ID("req")),
				jen.Line(),
				utils.AssertEqual(jen.ID("res").Dot("Code"), jen.Qual("net/http", "StatusInternalServerError"), nil),
				utils.AssertEmpty(jen.ID("res").Dot("Header").Call().Dot("Get").Call(jen.Lit("Set-Cookie")), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with error building cookie and error encoding cookie response"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("cb").Assign().VarPointer().ID("mockCookieEncoderDecoder").Values(),
				jen.ID("cb").Dot("On").Callln(
					jen.Lit("Encode"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.Lit(""), jen.Qual("errors", "New").Call(jen.Lit("blah"))),
				jen.ID("s").Dot("cookieManager").Equals().ID("cb"),
				jen.Line(),
				jen.ID("ed").Assign().VarPointer().Qual(proj.InternalEncodingV1Package("mock"), "EncoderDecoder").Values(),
				jen.ID("ed").Dot("On").Callln(
					jen.Lit("EncodeResponse"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything")).Dot("Return").Call(jen.Qual("errors", "New").Call(jen.Lit("blah"))),
				jen.ID("s").Dot("encoderDecoder").Equals().ID("ed"),
				jen.Line(),
				jen.ID("expectedUser").Assign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc())),
				jen.ID("s").Dot("userDB").Assert(jen.PointerTo().Qual(proj.ModelsV1Package("mock"), "UserDataManager")).Dot("On").Callln(
					jen.Lit("GetUserByUsername"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.ID("expectedUser").Dot("Username"),
				).Dot("Return").Call(jen.ID("expectedUser"), jen.Nil()),
				jen.Line(),
				jen.ID("s").Dot("authenticator").Assert(jen.PointerTo().Qual(proj.InternalAuthV1Package("mock"), "Authenticator")).Dot("On").Callln(
					jen.Lit("ValidateLogin"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.ID("true"), jen.Nil()),
				jen.Line(),
				jen.ID("exampleLoginData").Assign().VarPointer().Qual(proj.ModelsV1Package(), "UserLoginInput").Valuesln(
					jen.ID("Username").MapAssign().ID("expectedUser").Dot("Username"),
					jen.ID("Password").MapAssign().Add(utils.FakePasswordFunc()),
					jen.ID("TOTPToken").MapAssign().Lit("123456"),
				),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.ID("res").Assign().ID("httptest").Dot("NewRecorder").Call(),
				jen.ID("req").Equals().ID("req").Dot("WithContext").Call(jen.Qual("context", "WithValue").Call(jen.ID("req").Dot("Context").Call(), jen.ID("UserLoginInputMiddlewareCtxKey"), jen.ID("exampleLoginData"))),
				jen.Line(),
				jen.ID("s").Dot("LoginHandler").Call().Call(jen.ID("res"), jen.ID("req")),
				jen.Line(),
				utils.AssertEqual(jen.ID("res").Dot("Code"), jen.Qual("net/http", "StatusInternalServerError"), nil),
				utils.AssertEmpty(jen.ID("res").Dot("Header").Call().Dot("Get").Call(jen.Lit("Set-Cookie")), nil),
			)),
		),
		jen.Line(),
	)

	ret.Add(
		jen.Func().ID("TestService_Logout").Params(jen.ID("T").ParamPointer().Qual("testing", "T")).Block(
			jen.ID("T").Dot("Parallel").Call(),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("happy path"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.List(jen.ID("c"), jen.Err()).Assign().ID("s").Dot("buildAuthCookie").Call(jen.VarPointer().Qual(proj.ModelsV1Package(), "User").Values(jen.ID("ID").MapAssign().Add(utils.FakeUint64Func()), jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc()))),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.ID("req").Dot("AddCookie").Call(jen.ID("c")),
				jen.ID("res").Assign().ID("httptest").Dot("NewRecorder").Call(),
				jen.Line(),
				jen.ID("s").Dot("LogoutHandler").Call().Call(jen.ID("res"), jen.ID("req")),
				jen.Line(),
				jen.ID("actualCookie").Assign().ID("res").Dot("Header").Call().Dot("Get").Call(jen.Lit("Set-Cookie")),
				utils.AssertContains(jen.ID("actualCookie"), jen.Lit("Max-Age=0"), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("without cookie"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.ID("res").Assign().ID("httptest").Dot("NewRecorder").Call(),
				jen.ID("s").Dot("LogoutHandler").Call().Call(jen.ID("res"), jen.ID("req")),
			)),
		),
		jen.Line(),
	)

	ret.Add(
		jen.Func().ID("TestService_fetchLoginDataFromRequest").Params(jen.ID("T").ParamPointer().Qual("testing", "T")).Block(
			jen.ID("T").Dot("Parallel").Call(),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("happy path"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("expectedUser").Assign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc())),
				jen.ID("s").Dot("userDB").Assert(jen.PointerTo().Qual(proj.ModelsV1Package("mock"), "UserDataManager")).Dot("On").Callln(
					jen.Lit("GetUserByUsername"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.ID("expectedUser").Dot("Username"),
				).Dot("Return").Call(jen.ID("expectedUser"), jen.Nil()),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.ID("exampleLoginData").Assign().VarPointer().Qual(proj.ModelsV1Package(), "UserLoginInput").Valuesln(
					jen.ID("Username").MapAssign().ID("expectedUser").Dot("Username"),
					jen.ID("Password").MapAssign().Add(utils.FakePasswordFunc()),
					jen.ID("TOTPToken").MapAssign().Lit("123456"),
				),
				jen.Line(),
				jen.ID("req").Equals().ID("req").Dot("WithContext").Call(jen.Qual("context", "WithValue").Call(jen.ID("req").Dot("Context").Call(), jen.ID("UserLoginInputMiddlewareCtxKey"), jen.ID("exampleLoginData"))),
				jen.List(jen.ID("loginData"), jen.Err()).Assign().ID("s").Dot("fetchLoginDataFromRequest").Call(jen.ID("req")),
				jen.Line(),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("loginData")),
				utils.AssertEqual(jen.ID("loginData").Dot("user"), jen.ID("expectedUser"), nil),
				utils.AssertNil(jen.Err(), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("without login data attached to request"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.List(jen.ID("_"), jen.Err()).Equals().ID("s").Dot("fetchLoginDataFromRequest").Call(jen.ID("req")),
				utils.AssertError(jen.Err(), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with DB error fetching user"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("expectedUser").Assign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc())),
				jen.ID("s").Dot("userDB").Assert(jen.PointerTo().Qual(proj.ModelsV1Package("mock"), "UserDataManager")).Dot("On").Callln(
					jen.Lit("GetUserByUsername"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.ID("expectedUser").Dot("Username"),
				).Dot("Return").Call(jen.Parens(jen.PointerTo().Qual(proj.ModelsV1Package(), "User")).Call(jen.Nil()), jen.Qual("database/sql", "ErrNoRows")),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.ID("exampleLoginData").Assign().VarPointer().Qual(proj.ModelsV1Package(), "UserLoginInput").Valuesln(
					jen.ID("Username").MapAssign().ID("expectedUser").Dot("Username"),
					jen.ID("Password").MapAssign().Add(utils.FakePasswordFunc()),
					jen.ID("TOTPToken").MapAssign().Lit("123456"),
				),
				jen.Line(),
				jen.ID("req").Equals().ID("req").Dot("WithContext").Call(jen.Qual("context", "WithValue").Call(jen.ID("req").Dot("Context").Call(), jen.ID("UserLoginInputMiddlewareCtxKey"), jen.ID("exampleLoginData"))),
				jen.List(jen.ID("_"), jen.Err()).Equals().ID("s").Dot("fetchLoginDataFromRequest").Call(jen.ID("req")),
				utils.AssertError(jen.Err(), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with error fetching user"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("expectedUser").Assign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc())),
				jen.ID("s").Dot("userDB").Assert(jen.PointerTo().Qual(proj.ModelsV1Package("mock"), "UserDataManager")).Dot("On").Callln(
					jen.Lit("GetUserByUsername"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.ID("expectedUser").Dot("Username"),
				).Dot("Return").Call(jen.Parens(jen.PointerTo().Qual(proj.ModelsV1Package(), "User")).Call(jen.Nil()), jen.Qual("errors", "New").Call(jen.Lit("blah"))),
				jen.Line(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodGet"), jen.Lit("http://todo.verygoodsoftwarenotvirus.ru/testing"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.ID("exampleLoginData").Assign().VarPointer().Qual(proj.ModelsV1Package(), "UserLoginInput").Valuesln(
					jen.ID("Username").MapAssign().ID("expectedUser").Dot("Username"),
					jen.ID("Password").MapAssign().Add(utils.FakePasswordFunc()),
					jen.ID("TOTPToken").MapAssign().Lit("123456"),
				),
				jen.Line(),
				jen.ID("req").Equals().ID("req").Dot("WithContext").Call(jen.Qual("context", "WithValue").Call(jen.ID("req").Dot("Context").Call(), jen.ID("UserLoginInputMiddlewareCtxKey"), jen.ID("exampleLoginData"))),
				jen.List(jen.ID("_"), jen.Err()).Equals().ID("s").Dot("fetchLoginDataFromRequest").Call(jen.ID("req")),
				utils.AssertError(jen.Err(), nil),
			)),
		),
		jen.Line(),
	)

	ret.Add(
		jen.Func().ID("TestService_validateLogin").Params(jen.ID("T").ParamPointer().Qual("testing", "T")).Block(
			jen.ID("T").Dot("Parallel").Call(),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("happy path"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("expected").Assign().ID("true"),
				utils.CreateCtx(),
				jen.ID("exampleInput").Assign().ID("loginData").Valuesln(
					jen.ID("loginInput").MapAssign().VarPointer().Qual(proj.ModelsV1Package(), "UserLoginInput").Valuesln(
						jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc()),
						jen.ID("Password").MapAssign().Add(utils.FakePasswordFunc()),
						jen.ID("TOTPToken").MapAssign().Lit("012345"),
					),
					jen.ID("user").MapAssign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(),
				),
				jen.Line(),
				jen.ID("s").Dot("authenticator").Assert(jen.PointerTo().Qual(proj.InternalAuthV1Package("mock"), "Authenticator")).Dot("On").Callln(
					jen.Lit("ValidateLogin"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.ID("expected"), jen.Nil()),
				jen.Line(),
				jen.List(jen.ID("actual"), jen.Err()).Assign().ID("s").Dot("validateLogin").Call(utils.CtxVar(), jen.ID("exampleInput")),
				utils.AssertEqual(jen.ID("expected"), jen.ID("actual"), nil),
				utils.AssertNoError(jen.Err(), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with too weak a password hash"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("expected").Assign().ID("true"),
				utils.CreateCtx(),
				jen.ID("exampleInput").Assign().ID("loginData").Valuesln(
					jen.ID("loginInput").MapAssign().VarPointer().Qual(proj.ModelsV1Package(), "UserLoginInput").Valuesln(
						jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc()),
						jen.ID("Password").MapAssign().Add(utils.FakePasswordFunc()),
						jen.ID("TOTPToken").MapAssign().Lit("012345"),
					),
					jen.ID("user").MapAssign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(),
				),
				jen.Line(),
				jen.ID("s").Dot("authenticator").Assert(jen.PointerTo().Qual(proj.InternalAuthV1Package("mock"), "Authenticator")).Dot("On").Callln(
					jen.Lit("ValidateLogin"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.ID("expected"), jen.Qual(proj.InternalAuthV1Package(), "ErrPasswordHashTooWeak")),
				jen.Line(),
				jen.ID("s").Dot("authenticator").Assert(jen.PointerTo().Qual(proj.InternalAuthV1Package("mock"), "Authenticator")).Dot("On").Callln(
					jen.Lit("HashPassword"), jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.Lit("blah"), jen.Nil()),
				jen.Line(),
				jen.ID("s").Dot("userDB").Assert(jen.PointerTo().Qual(proj.ModelsV1Package("mock"), "UserDataManager")).Dot("On").Callln(
					jen.Lit("UpdateUser"), jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.Nil()),
				jen.Line(),
				jen.List(jen.ID("actual"), jen.Err()).Assign().ID("s").Dot("validateLogin").Call(utils.CtxVar(), jen.ID("exampleInput")),
				utils.AssertEqual(jen.ID("expected"), jen.ID("actual"), nil),
				utils.AssertNoError(jen.Err(), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with too weak a password hash and error hashing the password"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("expected").Assign().ID("false"),
				jen.ID("expectedErr").Assign().Qual("errors", "New").Call(jen.Lit("arbitrary")),
				utils.CreateCtx(),
				jen.ID("exampleInput").Assign().ID("loginData").Valuesln(
					jen.ID("loginInput").MapAssign().VarPointer().Qual(proj.ModelsV1Package(), "UserLoginInput").Valuesln(
						jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc()),
						jen.ID("Password").MapAssign().Add(utils.FakePasswordFunc()),
						jen.ID("TOTPToken").MapAssign().Lit("012345"),
					),
					jen.ID("user").MapAssign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(),
				),
				jen.Line(),
				jen.ID("s").Dot("authenticator").Assert(jen.PointerTo().Qual(proj.InternalAuthV1Package("mock"), "Authenticator")).Dot("On").Callln(
					jen.Lit("ValidateLogin"), jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.ID("true"), jen.Qual(proj.InternalAuthV1Package(), "ErrPasswordHashTooWeak")),
				jen.Line(),
				jen.ID("s").Dot("authenticator").Assert(jen.PointerTo().Qual(proj.InternalAuthV1Package("mock"), "Authenticator")).Dot("On").Callln(
					jen.Lit("HashPassword"), jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.Lit(""), jen.ID("expectedErr")),
				jen.Line(),
				jen.List(jen.ID("actual"), jen.Err()).Assign().ID("s").Dot("validateLogin").Call(utils.CtxVar(), jen.ID("exampleInput")),
				utils.AssertEqual(jen.ID("expected"), jen.ID("actual"), nil),
				utils.AssertError(jen.Err(), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with too weak a password hash and error updating user"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("expected").Assign().ID("false"),
				jen.ID("expectedErr").Assign().Qual("errors", "New").Call(jen.Lit("arbitrary")),
				utils.CreateCtx(),
				jen.ID("exampleInput").Assign().ID("loginData").Valuesln(
					jen.ID("loginInput").MapAssign().VarPointer().Qual(proj.ModelsV1Package(), "UserLoginInput").Valuesln(
						jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc()),
						jen.ID("Password").MapAssign().Add(utils.FakePasswordFunc()),
						jen.ID("TOTPToken").MapAssign().Lit("012345"),
					),
					jen.ID("user").MapAssign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(),
				),
				jen.Line(),
				jen.ID("s").Dot("authenticator").Assert(jen.PointerTo().Qual(proj.InternalAuthV1Package("mock"), "Authenticator")).Dot("On").Callln(
					jen.Lit("ValidateLogin"), jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.ID("true"), jen.Qual(proj.InternalAuthV1Package(), "ErrPasswordHashTooWeak")),
				jen.Line(),
				jen.ID("s").Dot("authenticator").Assert(jen.PointerTo().Qual(proj.InternalAuthV1Package("mock"), "Authenticator")).Dot("On").Callln(
					jen.Lit("HashPassword"), jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.Lit("blah"), jen.Nil()),
				jen.Line(),
				jen.ID("s").Dot("userDB").Assert(jen.PointerTo().Qual(proj.ModelsV1Package("mock"), "UserDataManager")).Dot("On").Callln(
					jen.Lit("UpdateUser"), jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.ID("expectedErr")),
				jen.Line(),
				jen.List(jen.ID("actual"), jen.Err()).Assign().ID("s").Dot("validateLogin").Call(utils.CtxVar(), jen.ID("exampleInput")),
				utils.AssertEqual(jen.ID("expected"), jen.ID("actual"), nil),
				utils.AssertError(jen.Err(), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with error validating login"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				utils.CreateCtx(),
				jen.ID("expected").Assign().ID("false"),
				jen.ID("expectedErr").Assign().Qual("errors", "New").Call(jen.Lit("arbitrary")),
				jen.ID("exampleInput").Assign().ID("loginData").Valuesln(
					jen.ID("loginInput").MapAssign().VarPointer().Qual(proj.ModelsV1Package(), "UserLoginInput").Valuesln(
						jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc()),
						jen.ID("Password").MapAssign().Add(utils.FakePasswordFunc()),
						jen.ID("TOTPToken").MapAssign().Lit("012345"),
					),
					jen.ID("user").MapAssign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(),
				),
				jen.Line(),
				jen.ID("s").Dot("authenticator").Assert(jen.PointerTo().Qual(proj.InternalAuthV1Package("mock"), "Authenticator")).Dot("On").Callln(
					jen.Lit("ValidateLogin"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.ID("expected"), jen.ID("expectedErr")),
				jen.Line(),
				jen.List(jen.ID("actual"), jen.Err()).Assign().ID("s").Dot("validateLogin").Call(utils.CtxVar(), jen.ID("exampleInput")),
				utils.AssertEqual(jen.ID("expected"), jen.ID("actual"), nil),
				utils.AssertError(jen.Err(), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with invalid login"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("expected").Assign().ID("false"),
				jen.ID("s").Dot("authenticator").Assert(jen.PointerTo().Qual(proj.InternalAuthV1Package("mock"), "Authenticator")).Dot("On").Callln(
					jen.Lit("ValidateLogin"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.ID("expected"), jen.Nil()),
				jen.Line(),
				utils.CreateCtx(),
				jen.ID("exampleInput").Assign().ID("loginData").Valuesln(
					jen.ID("loginInput").MapAssign().VarPointer().Qual(proj.ModelsV1Package(), "UserLoginInput").Valuesln(
						jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc()),
						jen.ID("Password").MapAssign().Add(utils.FakePasswordFunc()),
						jen.ID("TOTPToken").MapAssign().Lit("012345"),
					),
					jen.ID("user").MapAssign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(),
				),
				jen.Line(),
				jen.List(jen.ID("actual"), jen.Err()).Assign().ID("s").Dot("validateLogin").Call(utils.CtxVar(), jen.ID("exampleInput")),
				utils.AssertEqual(jen.ID("expected"), jen.ID("actual"), nil),
				utils.AssertNoError(jen.Err(), nil),
			)),
		),
		jen.Line(),
	)

	ret.Add(
		jen.Func().ID("TestService_buildCookie").Params(jen.ID("T").ParamPointer().Qual("testing", "T")).Block(
			jen.ID("T").Dot("Parallel").Call(),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("happy path"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("exampleInput").Assign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc())),
				jen.List(jen.ID("cookie"), jen.Err()).Assign().ID("s").Dot("buildAuthCookie").Call(jen.ID("exampleInput")),
				utils.AssertNotNil(jen.ID("cookie"), nil),
				utils.AssertNoError(jen.Err(), nil),
			)),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("with error encoding"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("cb").Assign().VarPointer().ID("mockCookieEncoderDecoder").Values(),
				jen.ID("cb").Dot("On").Callln(
					jen.Lit("Encode"), jen.Qual("github.com/stretchr/testify/mock", "Anything"),
					jen.Qual("github.com/stretchr/testify/mock", "Anything"),
				).Dot("Return").Call(jen.Lit(""), jen.Qual("errors", "New").Call(jen.Lit("blah"))),
				jen.ID("s").Dot("cookieManager").Equals().ID("cb"),
				jen.Line(),
				jen.ID("exampleInput").Assign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc())),
				jen.List(jen.ID("cookie"), jen.Err()).Assign().ID("s").Dot("buildAuthCookie").Call(jen.ID("exampleInput")),
				utils.AssertNil(jen.ID("cookie"), nil),
				utils.AssertError(jen.Err(), nil),
			)),
		),
		jen.Line(),
	)

	ret.Add(
		jen.Func().ID("TestService_CycleSecret").Params(jen.ID("T").ParamPointer().Qual("testing", "T")).Block(
			jen.ID("T").Dot("Parallel").Call(),
			jen.Line(),
			jen.ID("T").Dot("Run").Call(jen.Lit("normal operation"), jen.Func().Params(jen.ID("t").ParamPointer().Qual("testing", "T")).Block(
				jen.ID("s").Assign().ID("buildTestService").Call(jen.ID("t")),
				jen.Line(),
				jen.ID("exampleUser").Assign().VarPointer().Qual(proj.ModelsV1Package(), "User").Values(jen.ID("ID").MapAssign().Add(utils.FakeUint64Func()), jen.ID("Username").MapAssign().Add(utils.FakeUsernameFunc())),
				jen.List(jen.ID("c"), jen.Err()).Assign().ID("s").Dot("buildAuthCookie").Call(jen.ID("exampleUser")),
				utils.AssertNotNil(jen.ID("c"), nil),
				utils.AssertNoError(jen.Err(), nil),
				jen.Line(),
				jen.Var().ID("ca").Qual(proj.ModelsV1Package(), "CookieAuth"),
				jen.ID("decodeErr").Assign().ID("s").Dot("cookieManager").Dot("Decode").Call(jen.ID("CookieName"), jen.ID("c").Dot("Value"), jen.VarPointer().ID("ca")),
				utils.AssertNoError(jen.ID("decodeErr"), nil),
				jen.Line(),
				jen.ID("res").Assign().ID("httptest").Dot("NewRecorder").Call(),
				jen.List(jen.ID("req"), jen.Err()).Assign().Qual("net/http", "NewRequest").Call(jen.Qual("net/http", "MethodPost"), jen.Lit("https://blah.com"), jen.Nil()),
				jen.Qual("github.com/stretchr/testify/require", "NotNil").Call(jen.ID("t"), jen.ID("req")),
				jen.Qual("github.com/stretchr/testify/require", "NoError").Call(jen.ID("t"), jen.Err()),
				jen.Line(),
				jen.ID("s").Dot("CycleSecretHandler").Call().Call(jen.ID("res"), jen.ID("req")),
				jen.Line(),
				jen.ID("decodeErr2").Assign().ID("s").Dot("cookieManager").Dot("Decode").Call(jen.ID("CookieName"), jen.ID("c").Dot("Value"), jen.VarPointer().ID("ca")),
				utils.AssertError(jen.ID("decodeErr2"), nil),
			)),
		),
		jen.Line(),
	)
	return ret
}
